/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
	name: string;
	email: string;
	password: string;
}
