/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */

export interface CreatePostDto {
	title: string;
	content: string;
	authorId: string;
}
