/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { PermissionConditions } from "./permissionConditions";
import type { RolePermission } from "./rolePermission";

export interface Permission {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	createdBy: string | null;
	/** @nullable */
	updatedBy: string | null;
	action: string;
	subject: string;
	fields: string[];
	/** @nullable */
	conditions: PermissionConditions;
	inverted: boolean;
	/** @nullable */
	reason: string | null;
	roles?: RolePermission[];
}
