/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { PostsControllerUpdate200AllOf } from "./postsControllerUpdate200AllOf";

export type PostsControllerUpdate200 = SuccessResponseDto & PostsControllerUpdate200AllOf;
