/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { PostDto } from "./postDto";

export type PostsControllerCreate201AllOf = {
	result?: PostDto;
};
