/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface Post {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	createdBy: string | null;
	/** @nullable */
	updatedBy: string | null;
	tenantId: string;
	title: string;
	content: string;
	published: boolean;
	author?: User;
	authorId: string;
}
