/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { PostsControllerCreate201AllOf } from "./postsControllerCreate201AllOf";

export type PostsControllerCreate201 = SuccessResponseDto & PostsControllerCreate201AllOf;
