/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { RolePermission } from "./rolePermission";
import type { RoleUser } from "./roleUser";

export interface Role {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	createdBy: string | null;
	/** @nullable */
	updatedBy: string | null;
	tenantId: string;
	name: string;
	/** @nullable */
	description: string | null;
	permissions?: RolePermission[];
	users?: RoleUser[];
}
