/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { Role } from "./role";
import type { Permission } from "./permission";

export interface RolePermission {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	createdBy: string | null;
	/** @nullable */
	updatedBy: string | null;
	role?: Role;
	roleId: string;
	permission?: Permission;
	permissionId: string;
}
