/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { UsersControllerCreate201AllOf } from "./usersControllerCreate201AllOf";

export type UsersControllerCreate201 = SuccessResponseDto & UsersControllerCreate201AllOf;
