/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { UsersControllerUpdate200AllOf } from "./usersControllerUpdate200AllOf";

export type UsersControllerUpdate200 = SuccessResponseDto & UsersControllerUpdate200AllOf;
