/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Nest React RBAC API
 * OpenAPI spec version: 1.0
 */
import type { TenantUser } from "./tenantUser";
import type { RoleUser } from "./roleUser";

export interface User {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	createdBy: string | null;
	/** @nullable */
	updatedBy: string | null;
	name: string;
	email: string;
	tenants?: TenantUser[];
	roles?: RoleUser[];
}
